spring.application.name=threadhub

spring.datasource.url=jdbc:postgresql://localhost:5432/threadhub
spring.datasource.username=threadhub_user
spring.datasource.password=threadhub_dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

